### PR TITLE
Add 5.2 file format import

### PR DESCRIPTION
**Pull request by silverailscolo**
Recognize new segment END marker (for track), no new features

### CODE REVIEW

**Comment by silverailscolo** [comment]
See JMRI Users groups.io messsage 183071 [XtrakCadReader does not work with XtrackCad 5.2.0 files](https://groups.io/g/jmriusers/message/183071)

**Review by bobjacobsen — APPROVED** [review]
Looks good.

**Comment by bobjacobsen** [comment]
I don't remember (or perhaps ever knew) the steps for releasing a new version of this. There does seem to be a [released 2.2.2 tag](https://github.com/JMRI/XTrkCadReader/releases/tag/v2.2.2) but I'm not sure what all it contains.

**Comment by bobjacobsen** [comment]
Is this ready to merge?

**Comment by mattharris** [comment]
> I don't remember (or perhaps ever knew) the steps for releasing a new version of this. There does seem to be a [released 2.2.2 tag](https://github.com/JMRI/XTrkCadReader/releases/tag/v2.2.2) but I'm not sure what all it contains.

@bobjacobsen there is a `dist` target in the ant build file that will create the zipped assets for release.

**Comment by silverailscolo** [comment]
I have the parts (a zipped jar) built locally. Will check my notes how I did this for the previous "release" on GitHub.

**Comment by silverailscolo** [comment]
Ready for merge (I don't have a Merge button for this repo).

**Comment by mattharris** [comment]
@silverailscolo given that you did not see a merge button, you probably do not have the appropriate permissions to make the release. I am happy to take this up if you wish.

**Comment by silverailscolo** [comment]
Thanks @mattharris I succeeded to make the release in Github via web. Must have been the Merge button hiding somewhere in the GitHub app where I didn't look. Will add a note in the release notes to inform all users. OP already received and tested the jar.
Egbert

**Pull request merged**
